/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/f1_2025_mclaren_mcl39.glb 
Author: shunqi (https://sketchfab.com/shunqi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f1-2025-mclaren-mcl39-c6194270002b401bb25be7e35ab56e34
Title: F1 2025 McLaren MCL39
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function F1Car(props) {
  const { nodes, materials } = useGLTF('/f1_2025_mclaren_mcl39-4k.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.647, -0.189, 1.466]} rotation={[1.571, 0.044, 0]} scale={[1, 0.994, 0.994]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.suspensions} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.suspensions} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_9.geometry} material={materials.rear_wing} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.drs_puller} />
      </group>
      <group position={[0.789, -0.183, 1.466]} rotation={[0, 0, 0.044]}>
        <mesh geometry={nodes.Object_24.geometry} material={materials['wheel_screw.001']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.wheel_screw} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.rear_tire} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.wheel_rim} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.rear_wheel_cover} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.wheel_nut} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.wheel_nut} />
      </group>
      <group position={[0.789, -0.183, 1.466]} rotation={[0, 0, 0.044]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials.wheel_screw} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.front_tire} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.front_wheel_cover} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['wheel_screw.001']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.wheel_rim} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.wheel_nut} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.wheel_nut} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.front_wheel_windlet} position={[0.636, -0.091, 1.44]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.front_wing} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.front_wing_c} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.exthaust} position={[0, -0.079, -2.195]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.headrest} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.main_body} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.mirror} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.cam_tbone_misc} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.halo} />
    </group>
  )
}

useGLTF.preload('/f1_2025_mclaren_mcl39-4k.glb')
